name: poupe_sempre
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.3.0
  cupertino_icons: ^1.0.0

  firebase_core: ^0.4.0+9
  firebase_analytics: ^5.0.2
  
  mask_text_input_formatter: ^1.1.0
  validadores: ^0.0.1
  cloud_firestore: ^0.13.0+1
  image_picker: ^0.6.7+14
  google_sign_in: ^4.1.1
  firebase_storage: ^3.1.1
  firebase_auth: ^0.15.3
  email_validator: ^1.0.6
  footer: ^0.0.3
  http: ^0.12.2
  date_format: ^1.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.8.0"

flutter:
  uses-material-design: true

  assets:
    - assets/reset-password-icon.png
    - assets/products/bolacha_recheada_cartoon.jpeg
    - assets/products/choco_leite_2.png
    - assets/products/choco_leite.png
    - assets/products/chocolate_hersheys.jpeg
    - assets/products/massa_caseira_rosane_2.jpg
    - assets/products/massa_caseiro_rosane.jpg